[[blockSQP2]]
arch = "aarch64"
git-tree-sha1 = "d3b95ba7bdda8a48f9720fb5576c96a82b380d4a"
os = "macos"

    [[blockSQP2.download]]
    sha256 = "4bc1db2ebb68fb06cbe45236d7170f42e488176b2822ba53087b04aec82b47ff"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.aarch64-apple-darwin.tar.gz"
[[blockSQP2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbc32d7ccdad4c9673c1390c265b3aced6cbf2f5"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "fd729f0c12a01132e5b7d57e51caefbbccf00432f7799a193de0fdd9de5dd902"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a897d64416658a3558b91fd544335fba3756f7f4"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "83cc76fd4838a418f99fa0f0a35f8e70458f7f04197f6fca026b1689a7128aa6"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e051fd18876865982d23d4ecfb4fa6cde410d5e0"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "1d302cc2f4e1df70ac4d9122716cdf52fae401d7c9d8566c1e8dbb05a9ebafcf"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88677d30df6f2035305a6c508e3b700f15123659"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "e7fe6ee368ea269561e5f7085bcd937020453b4709621848f097e20a1bf717ac"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
git-tree-sha1 = "6110df641f8fd9110068fd027f50533281953841"
os = "macos"

    [[blockSQP2.download]]
    sha256 = "cf5b4ac90e16b09042d01fe1dd458e29e3fbb0e99a8200322ef104eb21e151c5"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.x86_64-apple-darwin.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10edeef2d706b7a55a9e93ca52b63e16f19dda17"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "d262376c8ab09a6f61eb44bea75d667e0b5a9ca202f50e628f6fb905792bbfbd"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f98c76dd6d6c8df313e3ded75e0fb8936476350d"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "176b8b58bf44ee124aab1d028c80c03a079fcadb076a3162ec2582b0a9f3372d"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.2+0/blockSQP2.v0.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
