[[blockSQP2]]
arch = "aarch64"
git-tree-sha1 = "457c218c5c08e891c8382b654816669d7308055f"
os = "macos"

    [[blockSQP2.download]]
    sha256 = "a572d0fbe5a951cedf44d773dc587b60a3f81fb0d2385231b0c1ae07a44d83fc"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.aarch64-apple-darwin.tar.gz"
[[blockSQP2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cf43ffc6e0a66981ed306828afdf79d389cb9eb"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "25239922c04a61a5ef275987fd4f52d76ccc0551fc6e48a58d0a9071f91f6c12"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.aarch64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6b606ba71cc3b8828059f6bd8343eddaa533e32"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "7b418cd36a7abe0e6b7c92e70e3788867253f203746cce2e9ea097d117a71d11"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fca7c41b849100e12ebba681372883d63c461150"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "e5b02362ea8a0845eccbba3fe85100454c452373bc4b20eec9790786ede3cac3"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[blockSQP2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3836df2e27589f1ee48f2dd056a0676929cf69f9"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "0a28c80745efd5d6622264c22fde51f32d5e259edfbc69888a74c55da8bc3dec"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.powerpc64le-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
git-tree-sha1 = "5c461ef5a1896d66ffe843f002bf3fbdd6dd248e"
os = "macos"

    [[blockSQP2.download]]
    sha256 = "1b9027a142433a9d6829a2ed16e2a43aec5f2eeb04979ecec7d9c9d258a3ccfa"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.x86_64-apple-darwin.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60496dc72ebac29af25ede117dba9eac60bee0e4"
libc = "glibc"
os = "linux"

    [[blockSQP2.download]]
    sha256 = "cd2f78ffcdabcb22dd71dec329040bb67b17b6c8d8ce1165e4c0bdb65f17c835"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.x86_64-linux-gnu-cxx11.tar.gz"
[[blockSQP2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9817194e38865bb8e72e1c0693be48cd7f691e5a"
os = "windows"

    [[blockSQP2.download]]
    sha256 = "b143fbddec6b3631b65452ddc649edd79b0bb6fa4c679ca033c31aa73b5f4adf"
    url = "https://github.com/ReWittmann/blockSQP2_jll/releases/download/blockSQP2-v0.1.27+0/blockSQP2.v0.1.27.x86_64-w64-mingw32-cxx11.tar.gz"
