# Autogenerated wrapper script for blockSQP2_jll for powerpc64le-linux-gnu-cxx11
export libblockSQP2_jl

using MUMPS_seq_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("blockSQP2")
JLLWrappers.@declare_library_product(libblockSQP2_jl, "libblockSQP2_jl.so")
function __init__()
    JLLWrappers.@generate_init_header(MUMPS_seq_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libblockSQP2_jl,
        "lib/libblockSQP2_jl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
