# Autogenerated wrapper script for blockSQP2_jll for x86_64-w64-mingw32-cxx11
export libblockSQP2_jl

using OpenBLAS_jll
using qpOASES_jll
JLLWrappers.@generate_wrapper_header("blockSQP2")
JLLWrappers.@declare_library_product(libblockSQP2_jl, "libblockSQP2_jl.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS_jll, qpOASES_jll)
    JLLWrappers.@init_library_product(
        libblockSQP2_jl,
        "bin\\libblockSQP2_jl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
